---

- hosts: netbox
  become: yes
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: "Installing Python 3.6"
    yum:
      name:
        - yum install centos-release-scl
        - yum install rh-python36
        - yum groupinstall “Development Tools”
        - yum install -y epel-release
      state: latest
  
  - name: "Create PostGres DB called netbox"
    raw: sudo -u postgres psql
    raw: CREATE DATABASE netbox;
    raw: CREATE USER netbox WITH PASSWORD 'N3tb0x';
    raw: GRANT ALL PRIVILEGES ON DATABASE netbox TO netbox;

  - name: "Install Git"
    yum:
      name:
        - yum install -y git

  - name: "mkdir /opt/netbox/netbox"
       name:
         
